# Generated by Django 5.2.8 on 2026-03-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_listing_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="image",
        ),
    ]
