# Generated by Django 5.2.8 on 2026-03-18 11:46

from django.db import migrations

def create_initial_categories(apps, schema_editor):
    # Retrieve the historical version of the Category model
    Category = apps.get_model('marketplace', 'Category')
    
    # Define the default categories for the marketplace
    default_categories = [
        'Textbooks', 
        'Electronics', 
        'Study Materials', 
        'Furniture', 
        'Others'
    ]
    
    # Use get_or_create to avoid duplicate entries if they already exist
    for cat_name in default_categories:
        Category.objects.get_or_create(name=cat_name)

class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_remove_listing_image"),
    ]

    operations = [
        # Execute the custom Python function during migration
        migrations.RunPython(create_initial_categories),
    ]