# Generated by Django 6.0.3 on 2026-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_initial_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Reserved", "Reserved"),
                    ("Sold", "Sold"),
                    ("Inactive", "Inactive"),
                ],
                default="Available",
                max_length=16,
            ),
        ),
    ]
